📦 Transformation Blocks Add to Canvas
kuwala-io/kuwala pull request #125
Opened 2022-05-03 13:39 UTC by arifluthfi16

Addition:

1. Added TransformationCatalog & TransformationBlock DTO for data handling
2. Created base node handler
3. Created add to canvas feature
4. Created empty modal for the configuration

2022-05-04 13:54 UTC, mattigrthr requested changes
### Keep styling close to designs

I feel we can easily keep the styling closer to the designs. In particular the icon is too big and the name of the transformation block not nicely aligned with small font size and regular (can be bold and bigger as well as aligned to the left).

Design:

![image](https://user-images.githubusercontent.com/28758040/166691456-99435281-71b4-4c7d-80ff-975d1d7df4ab.png)

Current implementation:

![image](https://user-images.githubusercontent.com/28758040/166691537-da7a8822-35d9-46d5-bc0f-66ce9c1c7250.png)

### Adding data blocks fails

When dragging a data source from the left onto the canvas the block isn't rendered properly.

![image](https://user-images.githubusercontent.com/28758040/166691865-15b5d684-5815-4431-acb9-15df6825824d.png)

2022-05-05 13:55 UTC, arifluthfi16 commented on kuwala/core/canvas/src/components/Nodes/TransformationBlock/TransformationBlock.js
> +                        />
Resolved by creating a common component `Icon`

2022-05-05 15:45 UTC, arifluthfi16 commented on kuwala/core/canvas/src/components/Nodes/TransformationBlock/TransformationBlock.js
> +                {/* BODY */}
Resolved by creating a general block component

2022-05-05 15:52 UTC, mattigrthr commented on kuwala/core/canvas/src/components/Common/Block/index.js
> +        title='Title',
Shouldn't have a default value as we want to make sure it is always passed down to the component.

2022-05-05 15:53 UTC, mattigrthr commented on kuwala/core/canvas/src/components/Common/Block/index.js
> +        primaryButtonOnclick,
Should be `primaryButtonOnClick`.

2022-05-05 15:54 UTC, mattigrthr commented on kuwala/core/canvas/src/components/Common/Block/index.js
> +        icon='cogs'
Same here, no default value to make sure it's always passed down.

2022-05-05 15:54 UTC, mattigrthr commented on kuwala/core/canvas/src/components/Common/Block/index.js
> +        return <></>
If something is not rendered do `return undefined`.

2022-05-05 15:56 UTC, mattigrthr commented on kuwala/core/canvas/src/components/Common/Block/index.js
> +        return <></>
Same here

2022-05-06 08:07 UTC, mattigrthr commented
### Disabled configure button

The `configure` button of a transformation block should be disabled as long as the block isn't connected to preceding blocks (see designs).

2022-05-06 09:35 UTC, mattigrthr approved these changes

2022-05-06 09:36 UTC, merged