Notebook: Save results as data set
kuwala-io/kuwala pull request #98
Opened 2022-02-13 01:17 UTC by SamDuan

In this PR, I added couple lines of code in the notebook for saving result dataframe as json, csv and parquet. The code to read the result back to spark datafram is also included. 

Related story: [#46](https://github.com/kuwala-io/kuwala/issues/46)

2022-02-14 19:06 UTC, mattigrthr requested changes
We should include the three methods into the `kuwala/core/jupyter/modules/common.py`. Then we can also use it directly in the `kuwala/core/jupyter/notebooks/poi_category_by_population.ipynb` example.

2022-02-18 00:29 UTC, SamDuan commented on kuwala/core/jupyter/notebooks/popularity_correlation.ipynb
> +    "result.write.format('json').save('../notebooks/output/result.json')\n",
Okay. Thanks for the feedback.

2022-02-18 03:20 UTC, SamDuan commented
@mattigrthr not sure if I'm missing something. Looks like only you can trigger the workflows for the new commits. If so, could you kick them off for me?

2022-02-21 12:03 UTC, SamDuan commented
@mattigrthr could you kick off the workflows for me again? The PR shall be ready to go.

2022-03-03 09:35 UTC, mattigrthr approved these changes
All tested and it's working like a charm! 👌🏽 Nicely done, @SamDuan! 🙌🏽

2022-03-03 09:36 UTC, merged